In [1]:
import librosa
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
max_len =11
def parse_func(s_example):
    features = {
                'mfcc2':tf.FixedLenFeature((20,11),tf.float32),
                'n_mfcc':tf.FixedLenFeature((), tf.int64),
                'word': tf.FixedLenFeature((), tf.string)
                }
    example = tf.parse_single_example(s_example, features=features)
    return example

In [3]:
mapping_strings = tf.constant(["bed", "cat", "happy"])
table = tf.contrib.lookup.index_table_from_tensor(mapping=mapping_strings)

def map2hot_vector(feature):
    word_string = feature.pop('word')
    word_index = table.lookup(word_string)
    feature['word_vector'] = tf.one_hot(word_index,3,dtype=tf.float32)
    return feature

In [4]:
data = tf.data.TFRecordDataset(['bed.tfrecords','cat.tfrecords','happy.tfrecords']).\
    shuffle(20000).map(parse_func).map(map2hot_vector).take(20)


In [5]:
for sample in data:
    word = sample['word_vector'].numpy()
    mfcc2= sample['mfcc2'].numpy()
    print(word,mfcc2.shape)

[1. 0. 0.] (20, 11)
[0. 0. 1.] (20, 11)
[1. 0. 0.] (20, 11)
[0. 1. 0.] (20, 11)
[1. 0. 0.] (20, 11)
[1. 0. 0.] (20, 11)
[0. 0. 1.] (20, 11)
[1. 0. 0.] (20, 11)
[1. 0. 0.] (20, 11)
[0. 0. 1.] (20, 11)
[1. 0. 0.] (20, 11)
[0. 1. 0.] (20, 11)
[0. 0. 1.] (20, 11)
[0. 1. 0.] (20, 11)
[0. 0. 1.] (20, 11)
[0. 0. 1.] (20, 11)
[0. 0. 1.] (20, 11)
[0. 0. 1.] (20, 11)
[0. 1. 0.] (20, 11)
[0. 1. 0.] (20, 11)
